<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="6745" started-at="2016-04-09T00:06:59Z" finished-at="2016-04-09T00:07:06Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="6745" started-at="2016-04-09T00:06:59Z" finished-at="2016-04-09T00:07:06Z">
      <class name="logHours.LogEffortsInJira">
        <test-method status="FAIL" signature="readXLTest()[pri:0, instance:logHours.LogEffortsInJira@c6a292]" name="readXLTest" is-config="true" duration-ms="0" started-at="2016-04-09T10:06:59Z" finished-at="2016-04-09T10:06:59Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at library.ReadData.getData(ReadData.java:47)
	at logHours.LogEffortsInJira.readXLTest(LogEffortsInJira.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readXLTest -->
        <test-method status="SKIP" signature="jiraLoginTest()[pri:1, instance:logHours.LogEffortsInJira@c6a292]" name="jiraLoginTest" duration-ms="1" started-at="2016-04-09T10:07:06Z" finished-at="2016-04-09T10:07:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- jiraLoginTest -->
        <test-method status="SKIP" signature="afterTest(org.testng.ITestResult)[pri:0, instance:logHours.LogEffortsInJira@c6a292]" name="afterTest" is-config="true" duration-ms="0" started-at="2016-04-09T10:07:06Z" finished-at="2016-04-09T10:07:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- logHours.LogEffortsInJira -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
